### PR TITLE
Push images to ECR

### PR DESCRIPTION
**Pull request by mpenick**
Add images to our private AWS ECR registry as part of the release process.

**Checklist**
- [X] Changes manually tested
- [ ] Automated Tests added/updated
- [x] Documentation added/updated
- [x] CLA Signed: [DataStax CLA](https://cla.datastax.com/)

### CODE REVIEW

**Comment by mpenick** [comment]
Still testing this.

**Comment by tatu-at-datastax** [comment]
Quick question: is this in addition to publishing to Docker Hub? I assume so, just verifying, since our users would be accessing images from some public registry.

**Comment by jeffreyscarpenter** [comment]
I'm -1 on pushing images to private registry from our public repo.

**Comment by tatu-at-datastax** [comment]
I think the problem here is that access to Dockerhub registry is unreliable due to rate limiting they do. So deployments can and do fail. This is not theoretical but actual problem being encountered and I remember this being a problem elsewhere too and (from what I understood) there is no simple solution.

So I think what we need is a some form of caching be that a completely separate registry, or some of pass-through cache.
It sounds like we should discuss the way we want to handle that.

**Pull request merged**
