### PR TITLE
fix quantiles check in the RestApiMetricsTest

### PR DESCRIPTION
**Pull request by ivansenic**
**What this PR does**:

Fixing missing quantiles support in the `RestApiMetricsTest`

**Which issue(s) this PR fixes**:
`v2.0.0` branch

### CODE REVIEW

**Review by jeffreyscarpenter — APPROVED** [review]
Good catch, thanks for the fix.

**Comment by ivansenic** [comment]
@jeffreyscarpenter @tatu-at-datastax Tests are not green due to the:

```
Step #4 - "cassandra-3.11": INFO  [process-runner-restapi-1-1] 2022-01-21 14:38:16,685 ProcessRunner.java:154 - RestAPI process 1/1 exited with return code 143
Step #4 - "cassandra-3.11": [INFO] 
Step #4 - "cassandra-3.11": [INFO] Results:
Step #4 - "cassandra-3.11": [INFO] 
Step #4 - "cassandra-3.11": [ERROR] Failures: 
Step #4 - "cassandra-3.11": [ERROR]   RestApiv2Test.getRowsWithUDT:1572->createTestTable:3408 
Step #4 - "cassandra-3.11": expected: 201
Step #4 - "cassandra-3.11":  but was: 400
Step #4 - "cassandra-3.11": [INFO] 
Step #4 - "cassandra-3.11": [ERROR] Tests run: 867, Failures: 1, Errors: 0, Skipped: 33
```
can I merge anyway? Or what's the procedure here?

**Comment by ivansenic** [comment]
Merging so @jeffreyscarpenter can work on top of this.. Hope that's fine with @tatu-at-datastax

**Comment by tatu-at-datastax** [comment]
@ivansenic Thank you for fixing this and explaining how it works -- I was not familiar with the way test customization works in Stargate so this is very helpful (I am more familiar with direct configuration by means other than system properties).

On green tests. We are not quite yet (but very close!) to all ITs running green. As Jeff suggested earlier, that one test failure is due to a new test merged via Stargate V1, and fix in v2.0.0 by Olivier hasn't yet been merged.
So yes please go ahead and merge this.

Fix makes sense as you explained: I was not familiar with the way we set up system properties.

**Pull request merged**
