### PR TITLE
Fix #630 - Inconsistent authentication error messages

### LINKED ISSUE #630: Inconsistent authentication error messages in REST API and DOC API
We appear to have inconsistent auth error reporting in Doc API vs. REST v1, e.g.:
REST v1:

```
{"description":"Role unauthorized for operation: Invalid clientID or hash provided","code":401}
```

Doc API:

```
You are not permitted to perform this action. Did you authenticate?
```

### PR DESCRIPTION
**Pull request by eribeiro**
Inconsistent auth messages in docsapi.

### CODE REVIEW

**Review by dimas-b — APPROVED** [review]

**Comment by dougwettlaufer** [comment]
Looks like there's some failing tests

```
Step #5 - "dse-6.8": [INFO] Results:
Step #5 - "dse-6.8": [INFO]
Step #5 - "dse-6.8": [ERROR] Failures:
Step #5 - "dse-6.8": [ERROR]   BaseDocumentApiV2Test.testInvalidDepthAndLength:464
Step #5 - "dse-6.8": Expecting:
Step #5 - "dse-6.8":  <"{"description":"Bad request: Max depth of 64 exceeded","code":400}">
Step #5 - "dse-6.8": to be equal to:
Step #5 - "dse-6.8":  <"Max depth of 64 exceeded">
Step #5 - "dse-6.8": but was not.
Step #5 - "dse-6.8": [ERROR]   BaseDocumentApiV2Test.testInvalidFullDocPageSize:2663
Step #5 - "dse-6.8": Expecting:
Step #5 - "dse-6.8":  <"{"description":"Bad request: The parameter `page-size` is limited to 20.","code":400}">
Step #5 - "dse-6.8": to be equal to:
Step #5 - "dse-6.8":  <"The parameter `page-size` is limited to 20.">
Step #5 - "dse-6.8": but was not.
Step #5 - "dse-6.8": [ERROR]   BaseDocumentApiV2Test.testInvalidKeyPut:261
Step #5 - "dse-6.8": Expecting:
Step #5 - "dse-6.8":  <"{"description":"Bad request: The characters [`[`, `]`, `,`, `.`, `'`, `*`] are not permitted in JSON field names, invalid field square[]braces","code":400}">
Step #5 - "dse-6.8": to be equal to:
Step #5 - "dse-6.8":  <"The characters [`[`, `]`, `,`, `.`, `'`, `*`] are not permitted in JSON field names, invalid field square[]braces">
Step #5 - "dse-6.8": but was not.
Step #5 - "dse-6.8": [ERROR]   BaseDocumentApiV2Test.testInvalidKeyspaceAndTable:237
Step #5 - "dse-6.8": Expecting:
Step #5 - "dse-6.8":  <"{"description":"Bad request: Unknown namespace unknown_keyspace_1337, you must create it first.","code":400}">
Step #5 - "dse-6.8": to be equal to:
Step #5 - "dse-6.8":  <"Unknown namespace unknown_keyspace_1337, you must create it first.">
Step #5 - "dse-6.8": but was not.
Step #5 - "dse-6.8": [ERROR]   BaseDocumentApiV2Test.testInvalidPatches:1280
Step #5 - "dse-6.8": Expecting:
Step #5 - "dse-6.8":  <"{"description":"Bad request: A patch operation must be done with a JSON object, not an array.","code":400}">
Step #5 - "dse-6.8": to be equal to:
Step #5 - "dse-6.8":  <"A patch operation must be done with a JSON object, not an array.">
Step #5 - "dse-6.8": but was not.
Step #5 - "dse-6.8": [ERROR]   BaseDocumentApiV2Test.testInvalidPuts:857
Step #5 - "dse-6.8": Expecting:
Step #5 - "dse-6.8":  <"{"description":"Bad request: Updating a key with just a JSON primitive, empty object, or empty array is not allowed. Found: 3\nHint: update the parent path with a defined object instead.","code":400}">
Step #5 - "dse-6.8": to be equal to:
Step #5 - "dse-6.8":  <"Updating a key with just a JSON primitive, empty object, or empty array is not allowed. Found: 3
Step #5 - "dse-6.8": Hint: update the parent path with a defined object instead.">
Step #5 - "dse-6.8": but was not.
Step #5 - "dse-6.8": [ERROR]   BaseDocumentApiV2Test.testInvalidSearch:1875
Step #5 - "dse-6.8": Expecting:
Step #5 - "dse-6.8":  <"{"description":"Bad request: Search was expecting a JSON object as input.","code":400}">
Step #5 - "dse-6.8": to be equal to:
Step #5 - "dse-6.8":  <"Search was expecting a JSON object as input.">
Step #5 - "dse-6.8": but was not.
Step #5 - "dse-6.8": [ERROR]   BaseDocumentApiV2Test.testPaginationDisallowedLimitedSupport:2685
Step #5 - "dse-6.8": Expecting:
Step #5 - "dse-6.8":  <"{"description":"Bad request: The results as requested must fit in one page, try increasing the `page-size` parameter.","code":400}">
Step #5 - "dse-6.8": to be equal to:
Step #5 - "dse-6.8":  <"The results as requested must fit in one page, try increasing the `page-size` parameter.">
Step #5 - "dse-6.8": but was not.
Step #5 - "dse-6.8": [ERROR]   DocumentApiV2Test>BaseDocumentApiV2Test.testInvalidDepthAndLength:464
Step #5 - "dse-6.8": Expecting:
Step #5 - "dse-6.8":  <"{"description":"Bad request: Max depth of 64 exceeded","code":400}">
Step #5 - "dse-6.8": to be equal to:
Step #5 - "dse-6.8":  <"Max depth of 64 exceeded">
Step #5 - "dse-6.8": but was not.
Step #5 - "dse-6.8": [ERROR]   DocumentApiV2Test>BaseDocumentApiV2Test.testInvalidFullDocPageSize:2663
Step #5 - "dse-6.8": Expecting:
Step #5 - "dse-6.8":  <"{"description":"Bad request: The parameter `page-size` is limited to 20.","code":400}">
Step #5 - "dse-6.8": to be equal to:
Step #5 - "dse-6.8":  <"The parameter `page-size` is limited to 20.">
Step #5 - "dse-6.8": but was not.
Step #5 - "dse-6.8": [ERROR]   DocumentApiV2Test>BaseDocumentApiV2Test.testInvalidKeyPut:261
Step #5 - "dse-6.8": Expecting:
Step #5 - "dse-6.8":  <"{"description":"Bad request: The characters [`[`, `]`, `,`, `.`, `'`, `*`] are not permitted in JSON field names, invalid field square[]braces","code":400}">
Step #5 - "dse-6.8": to be equal to:
Step #5 - "dse-6.8":  <"The characters [`[`, `]`, `,`, `.`, `'`, `*`] are not permitted in JSON field names, invalid field square[]braces">
Step #5 - "dse-6.8": but was not.
Step #5 - "dse-6.8": [ERROR]   DocumentApiV2Test>BaseDocumentApiV2Test.testInvalidKeyspaceAndTable:237
Step #5 - "dse-6.8": Expecting:
Step #5 - "dse-6.8":  <"{"description":"Bad request: Unknown namespace unknown_keyspace_1337, you must create it first.","code":400}">
Step #5 - "dse-6.8": to be equal to:
Step #5 - "dse-6.8":  <"Unknown namespace unknown_keyspace_1337, you must create it first.">
Step #5 - "dse-6.8": but was not.
Step #5 - "dse-6.8": [ERROR]   DocumentApiV2Test>BaseDocumentApiV2Test.testInvalidPatches:1280
Step #5 - "dse-6.8": Expecting:
Step #5 - "dse-6.8":  <"{"description":"Bad request: A patch operation must be done with a JSON object, not an array.","code":400}">
Step #5 - "dse-6.8": to be equal to:
Step #5 - "dse-6.8":  <"A patch operation must be done with a JSON object, not an array.">
Step #5 - "dse-6.8": but was not.
Step #5 - "dse-6.8": [ERROR]   DocumentApiV2Test>BaseDocumentApiV2Test.testInvalidPuts:857
Step #5 - "dse-6.8": Expecting:
Step #5 - "dse-6.8":  <"{"description":"Bad request: Updating a key with just a JSON primitive, empty object, or empty array is not allowed. Found: 3\nHint: update the parent path with a defined object instead.","code":400}">
Step #5 - "dse-6.8": to be equal to:
Step #5 - "dse-6.8":  <"Updating a key with just a JSON primitive, empty object, or empty array is not allowed. Found: 3
Step #5 - "dse-6.8": Hint: update the parent path with a defined object instead.">
Step #5 - "dse-6.8": but was not.
Step #5 - "dse-6.8": [ERROR]   DocumentApiV2Test>BaseDocumentApiV2Test.testInvalidSearch:1875
Step #5 - "dse-6.8": Expecting:
Step #5 - "dse-6.8":  <"{"description":"Bad request: Search was expecting a JSON object as input.","code":400}">
Step #5 - "dse-6.8": to be equal to:
Step #5 - "dse-6.8":  <"Search was expecting a JSON object as input.">
Step #5 - "dse-6.8": but was not.
Step #5 - "dse-6.8": [ERROR]   DocumentApiV2Test>BaseDocumentApiV2Test.testPaginationDisallowedLimitedSupport:2685
Step #5 - "dse-6.8": Expecting:
Step #5 - "dse-6.8":  <"{"description":"Bad request: The results as requested must fit in one page, try increasing the `page-size` parameter.","code":400}">
Step #5 - "dse-6.8": to be equal to:
Step #5 - "dse-6.8":  <"The results as requested must fit in one page, try increasing the `page-size` parameter.">
Step #5 - "dse-6.8": but was not.
Step #5 - "dse-6.8": [ERROR]   DocumentApiV2TestDisable2i>BaseDocumentApiV2Test.testInvalidDepthAndLength:464
Step #5 - "dse-6.8": Expecting:
Step #5 - "dse-6.8":  <"{"description":"Bad request: Max depth of 64 exceeded","code":400}">
Step #5 - "dse-6.8": to be equal to:
Step #5 - "dse-6.8":  <"Max depth of 64 exceeded">
Step #5 - "dse-6.8": but was not.
Step #5 - "dse-6.8": [ERROR]   DocumentApiV2TestDisable2i>BaseDocumentApiV2Test.testInvalidFullDocPageSize:2663
Step #5 - "dse-6.8": Expecting:
Step #5 - "dse-6.8":  <"{"description":"Bad request: The parameter `page-size` is limited to 20.","code":400}">
Step #5 - "dse-6.8": to be equal to:
Step #5 - "dse-6.8":  <"The parameter `page-size` is limited to 20.">
Step #5 - "dse-6.8": but was not.
Step #5 - "dse-6.8": [ERROR]   DocumentApiV2TestDisable2i>BaseDocumentApiV2Test.testInvalidKeyPut:261
Step #5 - "dse-6.8": Expecting:
Step #5 - "dse-6.8":  <"{"description":"Bad request: The characters [`[`, `]`, `,`, `.`, `'`, `*`] are not permitted in JSON field names, invalid field square[]braces","code":400}">
Step #5 - "dse-6.8": to be equal to:
Step #5 - "dse-6.8":  <"The characters [`[`, `]`, `,`, `.`, `'`, `*`] are not permitted in JSON field names, invalid field square[]braces">
Step #5 - "dse-6.8": but was not.
Step #5 - "dse-6.8": [ERROR]   DocumentApiV2TestDisable2i>BaseDocumentApiV2Test.testInvalidKeyspaceAndTable:237
Step #5 - "dse-6.8": Expecting:
Step #5 - "dse-6.8":  <"{"description":"Bad request: Unknown namespace unknown_keyspace_1337, you must create it first.","code":400}">
Step #5 - "dse-6.8": to be equal to:
Step #5 - "dse-6.8":  <"Unknown namespace unknown_keyspace_1337, you must create it first.">
Step #5 - "dse-6.8": but was not.
Step #5 - "dse-6.8": [ERROR]   DocumentApiV2TestDisable2i>BaseDocumentApiV2Test.testInvalidPatches:1280
Step #5 - "dse-6.8": Expecting:
Step #5 - "dse-6.8":  <"{"description":"Bad request: A patch operation must be done with a JSON object, not an array.","code":400}">
Step #5 - "dse-6.8": to be equal to:
Step #5 - "dse-6.8":  <"A patch operation must be done with a JSON object, not an array.">
Step #5 - "dse-6.8": but was not.
Step #5 - "dse-6.8": [ERROR]   DocumentApiV2TestDisable2i>BaseDocumentApiV2Test.testInvalidPuts:857
Step #5 - "dse-6.8": Expecting:
Step #5 - "dse-6.8":  <"{"description":"Bad request: Updating a key with just a JSON primitive, empty object, or empty array is not allowed. Found: 3\nHint: update the parent path with a defined object instead.","code":400}">
Step #5 - "dse-6.8": to be equal to:
Step #5 - "dse-6.8":  <"Updating a key with just a JSON primitive, empty object, or empty array is not allowed. Found: 3
Step #5 - "dse-6.8": Hint: update the parent path with a defined object instead.">
Step #5 - "dse-6.8": but was not.
Step #5 - "dse-6.8": [ERROR]   DocumentApiV2TestDisable2i>BaseDocumentApiV2Test.testInvalidSearch:1875
Step #5 - "dse-6.8": Expecting:
Step #5 - "dse-6.8":  <"{"description":"Bad request: Search was expecting a JSON object as input.","code":400}">
Step #5 - "dse-6.8": to be equal to:
Step #5 - "dse-6.8":  <"Search was expecting a JSON object as input.">
Step #5 - "dse-6.8": but was not.
Step #5 - "dse-6.8": [ERROR]   DocumentApiV2TestDisable2i>BaseDocumentApiV2Test.testPaginationDisallowedLimitedSupport:2685
Step #5 - "dse-6.8": Expecting:
Step #5 - "dse-6.8":  <"{"description":"Bad request: The results as requested must fit in one page, try increasing the `page-size` parameter.","code":400}">
Step #5 - "dse-6.8": to be equal to:
Step #5 - "dse-6.8":  <"The results as requested must fit in one page, try increasing the `page-size` parameter.">
```

**Comment by eribeiro** [comment]
Ouch! My bad, I should have tested on DSE.

**Comment by dimas-b** [comment]
@eribeiro : Sorry about Mac trouble. Unfortunately, I do not have a Mac env to debug this in. However, it should be possible to run integration tests with a manually-managed DSE node as outlined in https://github.com/stargate/stargate/blob/master/DEV_GUIDE.md#debugging-integration-tests

Basically, just run DSE standalone and pass those `-Dstargate.test.backend.*` options to Maven. Hope it helps :)

**Comment by eribeiro** [comment]
Hi, even after I run the integration tests multiple times, I am still stuck on the following errors. Anyone could help me understand why those two tests are failing? I see these two lines are breaking on `Found: 3\nHint` but why the other similar tests pass? 

```bash
[ERROR] Failures:
[ERROR]   DocumentApiV2Test>BaseDocumentApiV2Test.testInvalidPatches:1308
Expecting:
 <"{"description":"Bad request: Updating a key with just a JSON primitive, empty object, or empty array is not allowed. Found: 3\nHint: update the parent path with a defined object instead.","code":400}">
to be equal to:
 <"{"description":"Bad request: Updating a key with just a JSON primitive, empty object, or empty array is not allowed. Found: 3
Hint: update the parent path with a defined object instead.","code":400}">
but was not.
[ERROR]   DocumentApiV2Test>BaseDocumentApiV2Test.testInvalidPuts:861
Expecting:
 <"{"description":"Bad request: Updating a key with just a JSON primitive, empty object, or empty array is not allowed. Found: 3\nHint: update the parent path with a defined object instead.","code":400}">
to be equal to:
 <"{"description":"Bad request: Updating a key with just a JSON primitive, empty object, or empty array is not allowed. Found: 3
Hint: update the parent path with a defined object instead.","code":400}">
but was not.
[INFO]
[ERROR] Tests run: 44, Failures: 2, Errors: 0, Skipped: 0
```

**Comment by dimas-b** [comment]
+1 to removing new lines in error messages :+1:

**Comment by eribeiro** [comment]
Hi, the tests were passing but I had to send last minute changes. Thanks!

**Review by dougwettlaufer — APPROVED** [review]

**Pull request merged**
