### PR TITLE
Improve code to help troubleshoot #1577, by more validation of UUID codec

### LINKED ISSUE #1577: Invalid UUID (0 bytes) served by gRPC for SGv2/REST API
Our perf tests for StargateV2/REST seem to have odd failures reported when accessing rows inserted: stack trace:

```
ERROR [dw-176 - GET /v2/keyspaces/baselines/iot?where=%7B%22machine_id%22%3A%7B%22%24eq%22%3A%2212d1012c-47fa-441c-a41e-87
3c048d2535%22%7D%2C%22sensor_name%22%3A%7B%22%24eq%22%3A%22wire_gauge%22%7D%7D&page-size=10] 2022-01-24 11:53:00,025 Defau
ltExceptionMapper.java:59 - Error handling a request: f9a67463d3518a01
java.lang.IllegalArgumentException: Expected 16 bytes for a uuid values, got 0
        at io.stargate.grpc.Values.uuid(Values.java:258)
        at io.stargate.sgv2.restsvc.grpc.FromProtoValueCodecs$UUIDCodec.fromProtoValue(FromProtoValueCodecs.java:368)
        at io.stargate.sgv2.restsvc.grpc.FromProtoConverter.mapFromProtoValues(FromProtoConverter.java:41)
        at io.stargate.sgv2.restsvc.resources.ResourceBase.convertRows(ResourceBase.java:157)
        at io.stargate.sgv2.restsvc.resources.ResourceBase.fetchRows(ResourceBase.java:146)
        at io.stargate.sgv2.restsvc.resources.Sgv2RowsResourceImpl.getRowWithWhere(Sgv2RowsResourceImpl.java:114)
```

which suggests that somehow either entries are stored incorrectly (corrupt data), or, perhaps more likely, that gRPC API is changing missing/null value into incorrect representation.

I have not been able to reproduce the issue with regular POSTs via REST API; data in this case is generated by Fallout tests, but not sure if it's via straight CQL or REST (sgv2) API.

Tests are here:

https://fallout.sjc.dsinternal.org/tests/ui/jenkins-dse@datastax.com/sgv2-http-rest-timeseries-cass4

### PR DESCRIPTION
**Pull request by tatu-at-datastax**
**What this PR does**:

Adds one more check to ensure invalid UUIDs decoding is caught by gRPC; also adds bit more testing.

**Which issue(s) this PR fixes**:

Does not fix, but hopefully helps to eventually fix #1577

**Checklist**
- [ ] Changes manually tested
- [x] Automated Tests added/updated
- [ ] Documentation added/updated
- [x] CLA Signed: [DataStax CLA](https://cla.datastax.com/)

### CODE REVIEW

**Review by mpenick — APPROVED** [review]

**Comment by tatu-at-datastax** [comment]
For some reason getting much more persistent JWT failures today.

**Pull request merged**
