### PR TITLE
Fix issues with passing `null`s through grpc for SGv2/REST

### PR DESCRIPTION
**Pull request by tatu-at-datastax**
**What this PR does**:

Fixes issue similar to #1558 in Stargate V1/REST, but for Stargate V2 (codebases differ wrt REST handling).

**Which issue(s) this PR fixes**:

Further fixes similar to #1558 work.

**Checklist**
- [ ] Changes manually tested
- [x] Automated Tests added/updated
- [ ] Documentation added/updated
- [ ] CLA Signed: [DataStax CLA](https://cla.datastax.com/)

### CODE REVIEW

**Comment by mpenick** [comment]
It looks like all CI backends are failing on the same test (and `ExecuteBatchTest` failed again on 4.0):

```
Step #4 - "dse-6.8": [ERROR] Failures: 
Step #4 - "dse-6.8": [ERROR]   RestApiv2Test.getRowsWithUDT:1572->createTestTable:3408 
Step #4 - "dse-6.8": expected: 201
Step #4 - "dse-6.8":  but was: 400
```

```
Step #4 - "cassandra-3.11": [ERROR] Failures: 
Step #4 - "cassandra-3.11": [ERROR]   RestApiv2Test.getRowsWithUDT:1572->createTestTable:3408 
Step #4 - "cassandra-3.11": expected: 201
Step #4 - "cassandra-3.11":  but was: 400
```

```
Step #4 - "cassandra-4.0": [ERROR] Failures: 
Step #4 - "cassandra-4.0": [ERROR]   RestApiv2Test.getRowsWithUDT:1572->createTestTable:3408 
Step #4 - "cassandra-4.0": expected: 201
Step #4 - "cassandra-4.0":  but was: 400
Step #4 - "cassandra-4.0": [ERROR] Errors: 
Step #4 - "cassandra-4.0": [ERROR]   CollectionsTest ? Server com.google.common.util.concurrent.UncheckedExecutionE...
Step #4 - "cassandra-4.0": [ERROR]   ExecuteBatchTest ? Server com.google.common.util.concurrent.UncheckedExecution...
Step #4 - "cassandra-4.0": [ERROR]   ExecuteBatchTest.simpleBatchAfterSchemaChange:116 ? StatusRuntime INTERNAL: co...
Step #4 - "cassandra-4.0": [ERROR]   ExecuteQueryTest ? Server com.google.common.util.concurrent.UncheckedExecution...
````

**Comment by mpenick** [comment]
Added an issue for the gRPC CI failures: https://github.com/stargate/stargate/issues/1568 with as much information as I currently have.

**Comment by tatu-at-datastax** [comment]
@mpenick Please note this is for Stargate V2: it has never had full green run. So those issues are being addressed separately.

**Comment by tatu-at-datastax** [comment]
Looks like all suggestions were addressed? It seems like a good to time to get this merged so others can more easily try it out.

**Review by mpenick — APPROVED** [review]

**Review by jeffreyscarpenter — APPROVED** [review]

**Pull request merged**
