### PR TITLE
relates to #1737: base github action for Docs API V2

### PR DESCRIPTION
**Pull request by ivansenic**
**What this PR does**:
Adds CI for the Docs V2 based on the GitHub actions.

**Which issue(s) this PR fixes**:
Relates to #1737

### CODE REVIEW

**Comment by ivansenic** [comment]
@tatu-at-datastax How does this actually works out, does this needs to be merged in order to check it out? Don't think so or?

**Comment by tatu-at-datastax** [comment]
@ivansenic no need to merge, there is an option to run action from specific branch in UI.

**Comment by ivansenic** [comment]
> @ivansenic no need to merge, there is an option to run action from specific branch in UI.
> 
> Although I guess in some cases merging is needed -- I think new workflows are only included from `master`. So if creating a new one it may be necessary to merge something, even just a placholder. And then UI will let you run it from any branch that has definition, I think.

@tatu-at-datastax but now I wrote the whole CI workflow.. Can I just merge this, would there be any side effects?

**Comment by mpenick** [comment]
Is this just temporary? I'm fine with it as long as this is eventually unified with the other apis CI and release process.

**Comment by ivansenic** [comment]
Thanks @mpenick, yes more improvements coming for sure..

**Pull request merged**
