### PR TITLE
(WIP) Test out if Jackson 2.15.2 would work with Stargate v2 + Quarkus

### PR DESCRIPTION
**Pull request by tatu-at-datastax**
WORK-IN-PROGRESS: not to be merged -- will upgrade to Jackson 2.15.2 when it's ready; for now testing Release Candidates.

**What this PR does**:

Upgrade Jackson dependency from 2.14.x (both Coordinator and APIs) to 2.15.2, to see that (or if) upgrade works wrt CI/IT.

**Which issue(s) this PR fixes**:

**Checklist**
- [x] Changes manually tested
- [ ] Automated Tests added/updated
- [ ] Documentation added/updated
- [ ] CLA Signed: [DataStax CLA](https://cla.datastax.com/)

### CODE REVIEW

**Comment by tatu-at-datastax** [comment]
Passes, although there is the odd part where use of SnakeYAML 2.0 seems to fail. Will need to see why.

**Comment by ivansenic** [comment]
are we closing this now?

**Comment by tatu-at-datastax** [comment]
@ivansenic I will probably need this (or similar) to test C*4/C*3.11 compatibility with SnakeYAML (and possibly DSE).
But will close as soon as practical.

**Comment by tatu-at-datastax** [comment]
Interesting. Only thing failing is Cassandra-3.11 starter test: other backends appear to work... or maybe our tests don't trigger falures.

**Comment by tatu-at-datastax** [comment]
Alas: does not look like any of backends works with SnakeYAML 2.0, without changes -- and if I read things right it is NOT possible to make code change that would work with both 1.33 and 2.0 as things are.
This does not prevent Jackson 2.15 upgrade, just need to override SnakeYAML dependency if using `jackson-dataformat-yaml` (which SGv2 APIs do not use).

**Comment by tatu-at-datastax** [comment]
Trying one more time with latest OSS Cassandra backends (3.11.15 / 4.0.10) that were just released: probably won't work; if so will just close the branch.

**Pull request closed without merging**
