### PR TITLE
Minor improvement to SGv2 API READMEs

### LINKED ISSUE #2098: Consistency in READMEs on how SGv2 API services are started
Make sure that the API services (REST, GraphQL, Docs API) have consistent documentation on how to run the API services for development and test task. The Docs API is more complete than GraphQL, may also want to review REST as well.

### PR DESCRIPTION
**Pull request by tatu-at-datastax**
**What this PR does**:

Improves READMEs of REST and GraphQL APIs (and minor rewording of Doc APIs) to address #2098.

**Which issue(s) this PR fixes**:
Fixes #2098

**Checklist**
- [ ] Changes manually tested
- [ ] Automated Tests added/updated
- [x] Documentation added/updated
- [x] CLA Signed: [DataStax CLA](https://cla.datastax.com/)

### CODE REVIEW

**Comment by tatu-at-datastax** [comment]
@jeffreyscarpenter Minimal changes, adding `../mvnw quarkus:dev` plus unifying README starts a bit.

**Review by ivansenic — COMMENTED** [review]
There is still a lot of difference in the readmes of the individual projects.. What's stopping us to align that? Maybe we can extract common parts to the `/apis/README.md` and then only discuss the differences in the each API? Or have "duplicated" content in all of the sub-projects?

I think we should at least align the `## Configuration properties` in all the projects right away.. Each project should reference the common props, and then add a `CONFIGURATION.md` for the specific properties of that project. This is very helpful in order to understand what's configurable and how..

**Comment by tatu-at-datastax** [comment]
@ivansenic I 100% agree we need to further improve. This would be just the minimal stopgap change.

**Comment by tatu-at-datastax** [comment]
Merging this just so we can get it out of the way. Not meant as the final version.

**Pull request merged**
