### PR TITLE
Update release-v2.yml

### PR DESCRIPTION
**Pull request by jeffreyscarpenter**
Rename the workflow so it won't be confused with v1 release workflow

### CODE REVIEW

**Review by tatu-at-datastax — APPROVED** [review]
Good idea. Might want to add "v1" for the default one unless it has it already?

**Comment by jeffreyscarpenter** [comment]
> Good idea. Might want to add "v1" for the default one unless it has it already?

I think it's better to leave the v1 release as-is.

**Comment by tatu-at-datastax** [comment]
> > Good idea. Might want to add "v1" for the default one unless it has it already?
> 
> I think it's better to leave the v1 release as-is.

I was only thinking of adding it in message, not label. But not a big deal either way.

**Pull request merged**
