### PR TITLE
Package integration tests as plain jar

### LINKED ISSUE #774: Publish integration tests as a normal jar with dependencies
Currently the Stargate integration tests are published as a "fat" jar with all the dependencies embedded.

This is sometimes inconvenient for downstream projects as it effectively prevents intelligent dependency management for test code.

Integration tests should be published as a normal jar with dependencies declared in its Maven manifest.

This way, downstream projects can control dependencies using regular build-time dependency management mechanisms.

### PR DESCRIPTION
**Pull request by dimas-b**
This is to allow clients to control dependencies in their build env.

* Move test code into the main/java dir
* Drop the fat testing*-all.jar

Note: this will make using JUnit5 console launcher more complicated,
but it is not expected to be a common use case. Downstream projects
usign Maven or other build tools should still be able to automatically
run all tests with their respective dependent libs (and also control
dependency versions).

Fixes #774

### CODE REVIEW

**Review by ivansenic — APPROVED** [review]
- run test from maven :ballot_box_with_check: 
- run test from IDE :ballot_box_with_check: 
- don't care about the junit console launcher.. :ballot_box_with_check: 

Btw, I noticed that the `ci/test.sh` does not use the maven wrapper, but mvn on the system, imo this is wrong.. I know it's not connected to this ticket, but maybe you could fix that as well..

I also get 4.0-beta4 missing on ccm (locally) 
```
[INFO] Running io.stargate.db.cassandra.impl.CassandraPersistenceIT
INFO  [main] 2021-04-09 11:10:55,396 ExternalStorage.java:107 - Creating storage cluster @io.stargate.it.storage.ClusterSpec(shared=true, nodes=1) for [engine:junit-jupiter]/[class:io.stargate.db.cassandra.impl.CassandraPersistenceIT]
ERROR [Exec Stream Pumper] 2021-04-09 11:10:55,661 CcmBridge.java:374 - ccmerr> 11:10:55,660 ccm WARNING Downloading 4.0-beta4 failed, trying to build from git instead.
ERROR [Exec Stream Pumper] 2021-04-09 11:10:55,662 CcmBridge.java:374 - ccmerr> The error was: Invalid version 4.0-beta4 (underlying error is: HTTP Error 404: Not Found)
ERROR [Exec Stream Pumper] 2021-04-09 11:11:49,514 CcmBridge.java:374 - ccmerr> 11:11:49,514 ccm ERROR Deleted /home/ise/.ccm/repository/gitCOLONcassandra-4.0-beta4 due to error
ERROR [Exec Stream Pumper] 2021-04-09 11:11:49,515 CcmBridge.java:374 - ccmerr> Traceback (most recent call last):
ERROR [Exec Stream Pumper] 2021-04-09 11:11:49,515 CcmBridge.java:374 - ccmerr>   File "/home/ise/.local/bin/ccm", line 112, in <module>
ERROR [Exec Stream Pumper] 2021-04-09 11:11:49,515 CcmBridge.java:374 - ccmerr>     cmd.run()
ERROR [Exec Stream Pumper] 2021-04-09 11:11:49,515 CcmBridge.java:374 - ccmerr>   File "/home/ise/.local/lib/python2.7/site-packages/ccmlib/cmds/cluster_cmds.py", line 135, in run
ERROR [Exec Stream Pumper] 2021-04-09 11:11:49,515 CcmBridge.java:374 - ccmerr>     cluster = Cluster(self.path, self.name, install_dir=self.options.install_dir, version=self.options.version, verbose=self.options.verbose)
ERROR [Exec Stream Pumper] 2021-04-09 11:11:49,515 CcmBridge.java:374 - ccmerr>   File "/home/ise/.local/lib/python2.7/site-packages/ccmlib/cluster.py", line 66, in __init__
ERROR [Exec Stream Pumper] 2021-04-09 11:11:49,515 CcmBridge.java:374 - ccmerr>     repo_dir, v = self.load_from_repository(version, verbose)
ERROR [Exec Stream Pumper] 2021-04-09 11:11:49,516 CcmBridge.java:374 - ccmerr>   File "/home/ise/.local/lib/python2.7/site-packages/ccmlib/cluster.py", line 85, in load_from_repository
ERROR [Exec Stream Pumper] 2021-04-09 11:11:49,516 CcmBridge.java:374 - ccmerr>     return repository.setup(version, verbose)
ERROR [Exec Stream Pumper] 2021-04-09 11:11:49,516 CcmBridge.java:374 - ccmerr>   File "/home/ise/.local/lib/python2.7/site-packages/ccmlib/repository.py", line 109, in setup
ERROR [Exec Stream Pumper] 2021-04-09 11:11:49,516 CcmBridge.java:374 - ccmerr>     clone_development(GIT_REPO, version, verbose=verbose)
ERROR [Exec Stream Pumper] 2021-04-09 11:11:49,516 CcmBridge.java:374 - ccmerr>   File "/home/ise/.local/lib/python2.7/site-packages/ccmlib/repository.py", line 268, in clone_development
ERROR [Exec Stream Pumper] 2021-04-09 11:11:49,516 CcmBridge.java:374 - ccmerr>     raise e
ERROR [Exec Stream Pumper] 2021-04-09 11:11:49,516 CcmBridge.java:374 - ccmerr> ccmlib.common.CCMError: Error compiling Cassandra. Is ant installed? See /home/ise/.ccm/repository/ccm-repository.log for details
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 54.147 s <<< FAILURE! - in io.stargate.db.cassandra.impl.CassandraPersistenceIT
[ERROR] io.stargate.db.cassandra.impl.CassandraPersistenceIT  Time elapsed: 54.147 s  <<< ERROR!
java.lang.RuntimeException: The command '[ccm, create, ccm_1, -i, 127.0.0., -n, 1:0, -v, 4.0-beta4, --config-dir=/tmp/ccm307527799013107928]' failed to execute
Caused by: org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
```
I also notice that package and then running test on a module does not work: `./mvnw clean package -D skipTests && /mvnw verify -pl testing`, but the jars exists in the `stargate-lib`, is there any maven magic to overcome this:
```
Failed to execute goal on project testing: Could not resolve dependencies for project io.stargate.it:testing:jar:1.0.19-SNAPSHOT: The following artifacts could not be resolved: io.stargate.db:persistence-test:jar:1.0.19-SNAPSHOT, io.stargate.db:persistence-api:jar:1.0.19-SNAPSHOT, io.stargate.auth.api:auth-api:jar:1.0.19-SNAPSHOT, io.stargate.web:restapi:jar:1.0.19-SNAPSHOT, io.stargate.starter:stargate-starter:jar:1.0.19-SNAPSHOT, io.stargate.it:testing-services:jar:1.0.19-SNAPSHOT: Could not find artifact io.stargate.db:persistence-test:jar:1.0.19-SNAPSHOT 
```

**Comment by dimas-b** [comment]
@ivansenic : the `ccm` error is very strange. What's your `ccm` version (and source repo)? If you try downloading Downloading http://archive.apache.org/dist/cassandra/4.0-beta4/apache-cassandra-4.0-beta4-bin.tar.gz directly in your env., does it work?

**Comment by dimas-b** [comment]
> [...] the ci/test.sh does not use the maven wrapper, but mvn on the system, [...]

@dougwettlaufer : was there any particular reason for using the system `mvn` binary as opposed to our local `mvnw` in CI?

**Comment by dimas-b** [comment]
> I also notice that package and then running test on a module does not work: ./mvnw clean package -D skipTests && /mvnw verify -pl testing, but the jars exists in the stargate-lib, is there any maven magic to overcome this:

AFAIK, running `./mvnw -pl testing verify` assumes dependencies are available from Maven repos (local + remote). For this command to work the other modules have to run the `./mvn install` command to be copied into the local maven repo. That's what I do. Alternatively, the `am` option in the `testing` command should help too.

**Review by mpenick — APPROVED** [review]
+1. This will make integrating gRPC tests easier too.

**Review by dougwettlaufer — APPROVED** [review]

**Comment by dougwettlaufer** [comment]
> > [...] the ci/test.sh does not use the maven wrapper, but mvn on the system, [...]
> 
> @dougwettlaufer : was there any particular reason for using the system `mvn` binary as opposed to our local `mvnw` in CI?

Not really. I just copied what I run locally which is the binary rather than the wrapper.

**Pull request merged**
