### PR TITLE
Update the high level arch guide per Paras

### PR DESCRIPTION
**Pull request by polandll**

### CODE REVIEW

**Comment by polandll** [comment]
Actually, I just realized that this diagram ONLY has DSE, and not Cassandra, so I'm waiting for a reply from Paras.

**Review by olim7t — APPROVED** [review]

**Comment by denisekgosnell** [comment]
@polandll and @dougwettlaufer It is great to show new backends that we support. However, I am -1 on switching the diagram to the one in the PR because it implies that Stargate only supports DSE.

A diagram that shows that we support DSE and different versions of Cassandra is okay.

**Review by dougwettlaufer — CHANGES_REQUESTED** [review]
Marking needs work to avoid accidentally merging before we get the new diagram.

**Comment by msmygit** [comment]
Also, what happened to the `gRPC*` and `Events*` based extensions? Shouldn't we include them back?

**Comment by dougwettlaufer** [comment]
Closing per discussion with @polandll

**Pull request closed without merging**
