### PR TITLE
Add a test case to reproduce #1577 fail on v2.0.0

### PR DESCRIPTION
**Pull request by tatu-at-datastax**
**What this PR does**:

Reproduces issue #1577

The key requirements are:

* Partition key has `UUID` value
* At least 2 entries are read; of these partition key for first is fine, second fails due to "empty" (by either gRPC server noticing, or sending malformed key)

Root cause is within gRPC service handlers but this reproduces it via REST/SGv2 since that is where it was first observed (as part of Fallout/Haxx perf test).

**Which issue(s) this PR fixes**:
Won't fix anything yet.

**Checklist**
- [ ] Changes manually tested
- [x] Automated Tests added/updated
- [ ] Documentation added/updated
- [x] CLA Signed: [DataStax CLA](https://cla.datastax.com/)

### CODE REVIEW

**Comment by tatu-at-datastax** [comment]
Ready for review, although we may want to wait for fix to #1577 which will go through StargateV1 (master branch).

**Comment by tatu-at-datastax** [comment]
One new test failure; we could check this in later as a regression test, or, could mark as `@Disabled`, change to enabled later on. Not sure what makes most sense.

**Comment by jeffreyscarpenter** [comment]
I don't have a major objection to this, although technically the underlying issue is a bug in the gRPC service. So why not add a test case that focuses on gRPC service rather than on REST service? Also, REST service is moving to the bridge. I guess adding it is not going to hurt anything, except perhaps continuing to add complexity to the IT test suite. If you do add now, agree adding `@Disabled` until #1577 fix is pushed down is a good choice.

**Comment by tatu-at-datastax** [comment]
@jeffreyscarpenter Fair question, and this is due to "backwards" reproductions: test was added before the root cause was known. There are now 2 other tests for gRPC directly (unit test, integration test) that do specifically check for the root cause.

I think I'd like to add this in addition only because of existing shallow coverage of some of the functionality -- we do not cover combinations of features. But I think I should probably extend this test slightly, to do actual pagination.

**Comment by jeffreyscarpenter** [comment]
> I think I'd like to add this in addition only because of existing shallow coverage of some of the functionality -- we do not cover combinations of features. But I think I should probably extend this test slightly, to do actual pagination.

Good point, agree.

**Pull request merged**
