### PR TITLE
Fix DSE ITs for Java 11

### PR DESCRIPTION
**Pull request by jeffreyscarpenter**
For Stargate 2.1, ITs using DSE fail with Java 11 because DSE fails on startup with the following error message:

```
java.lang.ClassNotFoundException: jdk.internal.misc.VM not found by io.stargate.db.dse
```

In #2628 @tatu-at-datastax made some progress on getting ITs to run for Stargate v2.1 branch by adding the `add-extends` directive to load specific modules. It appears that for DSE tests to pass we actually need deeper access to non-public classes. This PR changes `add-extends` to `add-opens` which allows the private access that DSE requires.

**Checklist**
- [x] Changes manually tested
- [x] Automated Tests added/updated
- [ ] Documentation added/updated
- [x] CLA Signed: [DataStax CLA](https://cla.datastax.com/)

### CODE REVIEW

**Comment by jeffreyscarpenter** [comment]
More detailed stack trace:

```
INFO  [docker-java-stream-1944903611] 2023-06-21 22:28:25,833 null:-1 - [COORDINATOR] STDOUT: ERROR: Bundle io.stargate.db.dse [1] EventDispatcher: Error during dispatch. (java.lang.ExceptionInInitializerError)
INFO  [docker-java-stream-1944903611] 2023-06-21 22:28:25,833 null:-1 - [COORDINATOR] STDERR: java.lang.ExceptionInInitializerError
INFO  [docker-java-stream-1944903611] 2023-06-21 22:28:25,834 null:-1 - [COORDINATOR] STDERR: 	at org.apache.cassandra.config.DatabaseDescriptor.<clinit>(DatabaseDescriptor.java:114)
INFO  [docker-java-stream-1944903611] 2023-06-21 22:28:25,834 null:-1 - [COORDINATOR] STDERR: 	at org.apache.cassandra.utils.time.ApolloTime.<clinit>(ApolloTime.java:32)
INFO  [docker-java-stream-1944903611] 2023-06-21 22:28:25,834 null:-1 - [COORDINATOR] STDERR: 	at org.apache.cassandra.utils.concurrent.AsyncRateLimiter.<init>(AsyncRateLimiter.java:96)
INFO  [docker-java-stream-1944903611] 2023-06-21 22:28:25,834 null:-1 - [COORDINATOR] STDERR: 	at org.apache.cassandra.config.NodeSyncConfig.<init>(NodeSyncConfig.java:60)
INFO  [docker-java-stream-1944903611] 2023-06-21 22:28:25,835 null:-1 - [COORDINATOR] STDERR: 	at org.apache.cassandra.config.Config.<init>(Config.java:497)
INFO  [docker-java-stream-1944903611] 2023-06-21 22:28:25,835 null:-1 - [COORDINATOR] STDERR: 	at io.stargate.db.dse.DsePersistenceActivator.makeConfig(DsePersistenceActivator.java:69)
INFO  [docker-java-stream-1944903611] 2023-06-21 22:28:25,835 null:-1 - [COORDINATOR] STDERR: 	at io.stargate.db.dse.DsePersistenceActivator.createService(DsePersistenceActivator.java:186)
INFO  [docker-java-stream-1944903611] 2023-06-21 22:28:25,835 null:-1 - [COORDINATOR] STDERR: 	at io.stargate.core.activator.BaseActivator.createServices(BaseActivator.java:243)
INFO  [docker-java-stream-1944903611] 2023-06-21 22:28:25,835 null:-1 - [COORDINATOR] STDERR: 	at io.stargate.core.activator.BaseActivator.startServiceInternal(BaseActivator.java:175)
INFO  [docker-java-stream-1944903611] 2023-06-21 22:28:25,835 null:-1 - [COORDINATOR] STDERR: 	at io.stargate.core.activator.BaseActivator$Tracker.startIfAllRegistered(BaseActivator.java:230)
INFO  [docker-java-stream-1944903611] 2023-06-21 22:28:25,835 null:-1 - [COORDINATOR] STDERR: 	at io.stargate.core.activator.BaseActivator$Tracker.addingService(BaseActivator.java:206)
INFO  [docker-java-stream-1944903611] 2023-06-21 22:28:25,835 null:-1 - [COORDINATOR] STDERR: 	at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:943)
INFO  [docker-java-stream-1944903611] 2023-06-21 22:28:25,835 null:-1 - [COORDINATOR] STDERR: 	at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:871)
INFO  [docker-java-stream-1944903611] 2023-06-21 22:28:25,835 null:-1 - [COORDINATOR] STDERR: 	at org.osgi.util.tracker.AbstractTracked.trackAdding(AbstractTracked.java:256)
INFO  [docker-java-stream-1944903611] 2023-06-21 22:28:25,835 null:-1 - [COORDINATOR] STDERR: 	at org.osgi.util.tracker.AbstractTracked.track(AbstractTracked.java:229)
INFO  [docker-java-stream-1944903611] 2023-06-21 22:28:25,835 null:-1 - [COORDINATOR] STDERR: 	at org.osgi.util.tracker.ServiceTracker$Tracked.serviceChanged(ServiceTracker.java:903)
INFO  [docker-java-stream-1944903611] 2023-06-21 22:28:25,836 null:-1 - [COORDINATOR] STDERR: 	at org.apache.felix.framework.EventDispatcher.invokeServiceListenerCallback(EventDispatcher.java:990)
INFO  [docker-java-stream-1944903611] 2023-06-21 22:28:25,838 null:-1 - [COORDINATOR] STDERR: 	at org.apache.felix.framework.EventDispatcher.fireEventImmediately(EventDispatcher.java:838)
INFO  [docker-java-stream-1944903611] 2023-06-21 22:28:25,840 null:-1 - [COORDINATOR] STDERR: 	at org.apache.felix.framework.EventDispatcher.fireServiceEvent(EventDispatcher.java:545)
INFO  [docker-java-stream-1944903611] 2023-06-21 22:28:25,840 null:-1 - [COORDINATOR] STDERR: 	at org.apache.felix.framework.Felix.fireServiceEvent(Felix.java:4833)
INFO  [docker-java-stream-1944903611] 2023-06-21 22:28:25,840 null:-1 - [COORDINATOR] STDERR: 	at org.apache.felix.framework.Felix.registerService(Felix.java:3804)
INFO  [docker-java-stream-1944903611] 2023-06-21 22:28:25,840 null:-1 - [COORDINATOR] STDERR: 	at org.apache.felix.framework.BundleContextImpl.registerService(BundleContextImpl.java:328)
INFO  [docker-java-stream-1944903611] 2023-06-21 22:28:25,840 null:-1 - [COORDINATOR] STDERR: 	at org.apache.felix.framework.BundleContextImpl.registerService(BundleContextImpl.java:302)
INFO  [docker-java-stream-1944903611] 2023-06-21 22:28:25,840 null:-1 - [COORDINATOR] STDERR: 	at io.stargate.core.activator.BaseActivator.startServiceInternal(BaseActivator.java:180)
INFO  [docker-java-stream-1944903611] 2023-06-21 22:28:25,840 null:-1 - [COORDINATOR] STDERR: 	at io.stargate.core.activator.BaseActivator.start(BaseActivator.java:103)
INFO  [docker-java-stream-1944903611] 2023-06-21 22:28:25,840 null:-1 - [COORDINATOR] STDERR: 	at org.apache.felix.framework.util.SecureAction.startActivator(SecureAction.java:698)
INFO  [docker-java-stream-1944903611] 2023-06-21 22:28:25,840 null:-1 - [COORDINATOR] STDERR: 	at org.apache.felix.framework.Felix.activateBundle(Felix.java:2402)
INFO  [docker-java-stream-1944903611] 2023-06-21 22:28:25,840 null:-1 - [COORDINATOR] STDERR: 	at org.apache.felix.framework.Felix.startBundle(Felix.java:2308)
INFO  [docker-java-stream-1944903611] 2023-06-21 22:28:25,840 null:-1 - [COORDINATOR] STDERR: 	at org.apache.felix.framework.BundleImpl.start(BundleImpl.java:998)
INFO  [docker-java-stream-1944903611] 2023-06-21 22:28:25,840 null:-1 - [COORDINATOR] STDERR: 	at org.apache.felix.framework.BundleImpl.start(BundleImpl.java:984)
INFO  [docker-java-stream-1944903611] 2023-06-21 22:28:25,840 null:-1 - [COORDINATOR] STDERR: 	at io.stargate.starter.Starter.start(Starter.java:466)
INFO  [docker-java-stream-1944903611] 2023-06-21 22:28:25,840 null:-1 - [COORDINATOR] STDERR: 	at io.stargate.starter.Starter.cli(Starter.java:658)
INFO  [docker-java-stream-1944903611] 2023-06-21 22:28:25,840 null:-1 - [COORDINATOR] STDERR: 	at io.stargate.starter.Starter.main(Starter.java:697)
INFO  [docker-java-stream-1944903611] 2023-06-21 22:28:25,841 null:-1 - [COORDINATOR] STDERR: Caused by: java.lang.RuntimeException: java.lang.ClassNotFoundException: jdk.internal.misc.VM not found by io.stargate.db.dse [1]
INFO  [docker-java-stream-1944903611] 2023-06-21 22:28:25,841 null:-1 - [COORDINATOR] STDERR: 	at org.apache.cassandra.utils.JavaVersionDependent.<clinit>(JavaVersionDependent.java:37)
INFO  [docker-java-stream-1944903611] 2023-06-21 22:28:25,842 null:-1 - [COORDINATOR] STDERR: 	... 33 more
INFO  [docker-java-stream-1944903611] 2023-06-21 22:28:25,843 null:-1 - [COORDINATOR] STDERR: Caused by: java.lang.ClassNotFoundException: jdk.internal.misc.VM not found by io.stargate.db.dse [1]
INFO  [docker-java-stream-1944903611] 2023-06-21 22:28:25,843 null:-1 - [COORDINATOR] STDERR: 	at org.apache.felix.framework.BundleWiringImpl.findClassOrResourceByDelegation(BundleWiringImpl.java:1597)
INFO  [docker-java-stream-1944903611] 2023-06-21 22:28:25,843 null:-1 - [COORDINATOR] STDERR: 	at org.apache.felix.framework.BundleWiringImpl.access$300(BundleWiringImpl.java:79)
INFO  [docker-java-stream-1944903611] 2023-06-21 22:28:25,843 null:-1 - [COORDINATOR] STDERR: 	at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.loadClass(BundleWiringImpl.java:1982)
INFO  [docker-java-stream-1944903611] 2023-06-21 22:28:25,843 null:-1 - [COORDINATOR] STDERR: 	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
INFO  [docker-java-stream-1944903611] 2023-06-21 22:28:25,843 null:-1 - [COORDINATOR] STDERR: 	at java.base/java.lang.Class.forName0(Native Method)
INFO  [docker-java-stream-1944903611] 2023-06-21 22:28:25,843 null:-1 - [COORDINATOR] STDERR: 	at java.base/java.lang.Class.forName(Unknown Source)
INFO  [docker-java-stream-1944903611] 2023-06-21 22:28:25,843 null:-1 - [COORDINATOR] STDERR: 	at org.apache.cassandra.utils.JavaVersionDependent.<clinit>(JavaVersionDependent.java:32)
INFO  [docker-java-stream-1944903611] 2023-06-21 22:28:25,843 null:-1 - [COORDINATOR] STDERR: 	... 33 more
```

**Review by ivansenic — COMMENTED** [review]
Seems it's still not working..

**Comment by jeffreyscarpenter** [comment]
I have not been successful in solving the test failures that are occurring on startup of Stargate with DSE and Java 11 despite multiple attempts. 

First, I tried incorporating the full list of `--add-opens` and `--add-exports` options that DSE uses (see section labeled `JPMS` in https://github.com/riptano/bdp/blob/6.8-dev/dse-db/conf/jvm11-server.options). The error still occurs.

In local testing, I had also noticed there was an initial warning on startup of `starctl` regarding accessing the `java.lang.reflect` package. I added an `-add-opens` for this as well. I then added the `--illegal-access=deny` flag to `starctl` and verified there are no other package access errors, but again the `ClassNotFoundException` still occurs.

Looking more closely at the root exception in the stack trace I noticed that it is a Felix `BundleClassLoader` that is generating this error. 

```
Caused by: java.lang.ClassNotFoundException: jdk.internal.misc.VM not found by io.stargate.db.dse [1]
	at org.apache.felix.framework.BundleWiringImpl.findClassOrResourceByDelegation(BundleWiringImpl.java:1591)
	at org.apache.felix.framework.BundleWiringImpl.access$300(BundleWiringImpl.java:79)
	at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.loadClass(BundleWiringImpl.java:1976)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:315)
	at org.apache.cassandra.utils.JavaVersionDependent.<clinit>(JavaVersionDependent.java:32)
```

So my next thought was whether this was an older version of Felix/OSGi that perhaps has issues with Java 11. I did not find any particular bug reports online but upgraded all the maven dependencies to the latest versions available. The error still occurs. 

At this point, I am not sure what else to check. Rather than focus additional effort on debugging this, it's probably best that we push forward with removal of Felix/OSGi as we had planned already.

**Comment by jeffreyscarpenter** [comment]
Closing this in favor of #2643

**Pull request closed without merging**
