### PR TITLE
(WIP) Fix #1263: add "-q" option for `gsutil` to remove progress bar noise.

### LINKED ISSUE #1263: Reduce noise from CI build wrt "gsutil rsync"
Current settings for cache init for Stargate CI jobs produce lots of noise as by default interactive progress bar/report is output. This can be disabled using `-q` (quiet) option, as outlined here:

https://cloud.google.com/storage/docs/gsutil/addlhelp/TopLevelCommandLineOptions

and should reduce log output noise a bit without losing useful information.
I will provide a patch.

### PR DESCRIPTION
**Pull request by tatu-at-datastax**
**What this PR does**:

Reduces CI test noise by adding "-q" (quiet) option. Also improves developer-doc/readme; was missing part of a range needed for Integration Tests to pass locally.

**Which issue(s) this PR fixes**:
Fixes #1263

**Checklist**
- [x] Changes manually tested (verified with CI run)
- [ ] Automated Tests added/updated - no tests for CI tests
- [ ] Documentation added/updated - no documentation for CI tests at this point

### CODE REVIEW

**Comment by tatu-at-datastax** [comment]
Will verify by looking at log output of CI tests here.

**Review by ivansenic — APPROVED** [review]
Merge once verified in the tests.. Maybe somebody with macOS should check the loopback addresses stuff, I never had to do that on linux..

**Comment by tatu-at-datastax** [comment]
@ivansenic I'll ask Jeff about it.

**Comment by tatu-at-datastax** [comment]
FWTW, this removed about 12,000 lines of logs for a typical Cassandra 4.0 CI run (checked; assuming 3.11 / DSE the same).

**Pull request merged**
