### PR TITLE
Fix #2569: update DSE dep 6.8.34 -> 6.8.35

### LINKED ISSUE #2569: Update to DSE 6.8.35
A new version of DSE has been released and should be used.

### PR DESCRIPTION
**Pull request by tatu-at-datastax**
**What this PR does**:

Updates DSE dependency to the latest released, 6.8.35.

**Which issue(s) this PR fixes**:
Fixes #2569

**Checklist**
- [x] Changes manually tested
- [ ] Automated Tests added/updated
- [ ] Documentation added/updated
- [x] CLA Signed: [DataStax CLA](https://cla.datastax.com/)

### CODE REVIEW

**Review by ivansenic — APPROVED** [review]
* should we build the new ci image?
* should this be based on `v1`?

**Comment by tatu-at-datastax** [comment]
> * should we build the new ci image?

Looked like 6.8.34 upgrade didn't make other changes. I can add more if necessary.

> * should this be based on `v1`?

We briefly discussed this on friday and thought we'd only want to make v1 changes when specifically required (on-demand). Plan is to get Classic/AD4D move to SGv2 (even if they still use in-coordinator API impls) so they would get upgrades this way.

**Comment by tatu-at-datastax** [comment]
@ivansenic v1 needed new build image (under `ci/`, `cloudbuild*`s). But does SGv2 have this any more?

**Comment by tatu-at-datastax** [comment]
> @tatu-at-datastax you r right, we moved to github actions on both branches, no ci image anymore..

ok thanks. Just wanted to make sure I didn't miss something obvious.

**Pull request merged**
