### PR TITLE
Upgrade dse version to 6.8.28

### LINKED ISSUE #2197: Update DSE to 6.8.28
A new version of DSE (6.8.27) has been released and should be used.

See release notes for issues resolved: https://github.com/datastax/release-notes/blob/master/DSE_6.8_Release_Notes.md#release-notes-for-6827

### PR DESCRIPTION
**Pull request by maheshrajamani**
**What this PR does**:
Upgrade dse version to 6.8.28

**Which issue(s) this PR fixes**:
Fixes #2197 

**Checklist**
- [ ] Changes manually tested
- [x] Automated Tests added/updated
- [ ] Documentation added/updated
- [x] CLA Signed: [DataStax CLA](https://cla.datastax.com/)

### CODE REVIEW

**Review by ivansenic — COMMENTED** [review]
This looks good.. In addition to this we need to:

* create new CI image that will use the new version, see `ci/README.md` for instructions
* create a PR for bumping the dse in the v2 apis

**Comment by ivansenic** [comment]
Maybe this gets fixed after #2212

**Comment by ivansenic** [comment]
> > * create new CI image that will use the new version, see `ci/README.md` for instructions
> 
> @ivansenic "make build push" fails in my local complaining for docker-ce. I have docker desktop installed, still if errors "E: Package 'docker-ce' has no installation candidate". Any thoughts?

Are you on windows? Anyway if you can not build it, I can tomorrow?

**Comment by maheshrajamani** [comment]
> Are you on windows? Anyway if you can not build it, I can tomorrow?

 I am on mac with M1 chip.

**Comment by versaurabh** [comment]
> @tatu-at-datastax We are getting here an:
> 
> ```
> Step #4 - "dse-6.8": [ERROR] Failed to execute goal on project persistence-dse-6.8: Could not resolve dependencies for project io.stargate.db.dse:persistence-dse-6.8:jar:1.0.68-SNAPSHOT: Failed to collect dependencies at com.datastax.dse:dse-core:jar:6.8.28: Failed to read artifact descriptor for com.datastax.dse:dse-core:jar:6.8.28: Could not transfer artifact com.datastax.dse:dse-core:pom:6.8.28 from/to artifactory-snapshots (https://repo.datastax.com/datastax-snapshots-local): authentication failed for https://repo.datastax.com/datastax-snapshots-local/com/datastax/dse/dse-core/6.8.28/dse-core-6.8.28.pom, status: 401 Unauthorized -> [Help 1]
> ```
> 
> Any idea what's going on? Is this some issue with the GCB? Works locally..

@ivansenic @tatu-at-datastax checking this PR

**Comment by versaurabh** [comment]
> RROR] Failed to execute goal on project persistence-dse-6.8

checking this

**Comment by versaurabh** [comment]
> @tatu-at-datastax We are getting here an:
> 
> ```
> Step #4 - "dse-6.8": [ERROR] Failed to execute goal on project persistence-dse-6.8: Could not resolve dependencies for project io.stargate.db.dse:persistence-dse-6.8:jar:1.0.68-SNAPSHOT: Failed to collect dependencies at com.datastax.dse:dse-core:jar:6.8.28: Failed to read artifact descriptor for com.datastax.dse:dse-core:jar:6.8.28: Could not transfer artifact com.datastax.dse:dse-core:pom:6.8.28 from/to artifactory-snapshots (https://repo.datastax.com/datastax-snapshots-local): authentication failed for https://repo.datastax.com/datastax-snapshots-local/com/datastax/dse/dse-core/6.8.28/dse-core-6.8.28.pom, status: 401 Unauthorized -> [Help 1]
> ```
> 
> Any idea what's going on? Is this some issue with the GCB? Works locally..

Checking this

**Comment by tatu-at-datastax** [comment]
I don't know why, but I suspect my removal of JFrog Maven repo might somehow be causing this.
It shouldn't really -- I don't think we should ever Maven install local snapshot builds to anywhere but local Maven repo (under `~/.m2/repo`) -- but it sounds like maybe that's what happens. Perhaps this is why that repo definition was not removed, or changed to standard Datastax repo.

But odd thing is that I don't think this problem happened with PR for Maven repo change. So I am not 100% sure that is causing this.

**Comment by ivansenic** [comment]
I updated the artfactory settings in the gcp secret, let's see if this helps..

**Comment by ivansenic** [comment]
@tatu-at-datastax My change did work, but broke the other CI.. I reverted.. The bug must be coming from that removal of the repositories in the previous PR. the only reason it works atm in other PR is due to the cached dependencies..

**Review by tatu-at-datastax — APPROVED** [review]

**Comment by tatu-at-datastax** [comment]
Ok so this did not make it in `2.0.1` but goes in next build hopefully.

**Comment by jeffreyscarpenter** [comment]
should we just skip this? I saw a Jira ticket created to update to 6.8.29

**Comment by tatu-at-datastax** [comment]
Might as well?

**Comment by ivansenic** [comment]
> should we just skip this? I saw a Jira ticket created to update to 6.8.29

Let's merge this and make a new PR for `6.8.29`. No harm to move step by step.

**Comment by tatu-at-datastax** [comment]
> > should we just skip this? I saw a Jira ticket created to update to 6.8.29
> 
> Let's merge this and make a new PR for `6.8.29`. No harm to move step by step.

This would also make it bit easier to see which version has the breakage, if something breaks.

**Comment by tatu-at-datastax** [comment]
@maheshrajamani I think we can go ahead with this PR now, before starting upgrade to the next version.

**Comment by tatu-at-datastax** [comment]
@maheshrajamani I think you also need to merge `v1` -> `main` (not done yet it seems)

**Pull request merged**
