### PR TITLE
Third part of #1644 fix: upgrade `dse-core` 6.8.16 -> 6.8.20

### PR DESCRIPTION
**Pull request by tatu-at-datastax**
**What this PR does**:

Third upgrade for https://github.com/stargate/stargate/issues/1644: DSE dependency from 6.8.16 to 6.8.20

**Which issue(s) this PR fixes**:

Part of fix for #1644

**Checklist**
- [ ] Changes manually tested
- [x] Automated Tests added/updated
- [ ] Documentation added/updated
- [x] CLA Signed: [DataStax CLA](https://cla.datastax.com/)

### CODE REVIEW

**Comment by tatu-at-datastax** [comment]
Unlike C*3.11.12 and C*4.0.3, looks like there are no regressions here.

**Review by ivansenic — APPROVED** [review]
Double checked that bugs found in the open-source Cassandra do not exist in DSE :+1: 

Having an update `README.md` would be nice as well, but I guess we can do that later..

**Comment by tatu-at-datastax** [comment]
@ivansenic question about "Having an update README.md" -- I did not see references to 6.8(.16) in main README, and there's no README under `persistence-dse-6.8`. I can make changes after merge (since there are 2 other PRs) but wanted to know what I missed.

**Comment by ivansenic** [comment]
> @ivansenic question about "Having an update README.md" -- I did not see references to 6.8(.16) in main README, and there's no README under `persistence-dse-6.8`. I can make changes after merge (since there are 2 other PRs) but wanted to know what I missed.

Yea I meant add a README.md in the `persistence-dse-6.8` so that we have a checklist next time we upgrade..

**Comment by tatu-at-datastax** [comment]
Ah. Yes, I think 4.0 is also missing README. Good point, I can add something via C4 PR.

**Pull request merged**
