### PR TITLE
Remove `auto-factory` dependency if possible; or if not, update version from pre-1.0 to 1.0.1

### PR DESCRIPTION
**Pull request by tatu-at-datastax**
**What this PR does**:

Removes dependencies by Cassandra-4.0 and DSE backends to `com.google.auto.factory:auto-factory`.
(if this was not possibly, would increase dependency version from 1.0-b7 (pre-1.0) to 1.0.1).

**Which issue(s) this PR fixes**:
No issue filed

**Checklist**
- [x] Changes manually tested -- rely on build, CI
- [ ] Automated Tests added/updated
- [ ] Documentation added/updated
- [x] CLA Signed: [DataStax CLA](https://cla.datastax.com/)

### CODE REVIEW

**Review by ivansenic — CHANGES_REQUESTED** [review]
I checked and I think we can delete this dependency. Seems not used by our modules and I see no transitive deps in the C and DSE.. Not sure why this was added. But please double check..

**Comment by tatu-at-datastax** [comment]
@ivansenic Ok I'll try to remove see what happens.

**Comment by tatu-at-datastax** [comment]
@ivansenic Removed dependency; CI passes, could you approve?

**Review by jeffreyscarpenter — APPROVED** [review]

**Review by ivansenic — APPROVED** [review]

**Comment by tatu-at-datastax** [comment]
Thanks!

**Pull request merged**
