### PR TITLE
Fix GH actions to run for v2.1 too

### PR DESCRIPTION
**Pull request by tatu-at-datastax**
**What this PR does**:

Fixes Github action applicability to get API tests to run for v2.1 too, not just v1/main/PRs.

**Which issue(s) this PR fixes**:

**Checklist**
- [ ] Changes manually tested
- [x] Automated Tests added/updated
- [ ] Documentation added/updated
- [x] CLA Signed: [DataStax CLA](https://cla.datastax.com/)

### CODE REVIEW

**Comment by tatu-at-datastax** [comment]
Problems with DSE backend remain, but not caused by this PR; merging since API tests are needed by other PRs.

**Comment by ivansenic** [comment]
These changes must be on `main` as well.. But it might work for pull requests if the base is `v2.1`.. Should be checked..

**Comment by tatu-at-datastax** [comment]
This has always been bit confusing for me, but I _think_ it's enough for changes to be in the branch being pushed (wrt pushes); for PRs applicability was already not limited.
But if it turns out it's not enough I (or whoever has chance) can merge it to `main` for sure.

**Comment by tatu-at-datastax** [comment]
When merging from `main` to `v2.1`, Coordinator test CI run is now triggered so I think we are good.

**Pull request merged**
