### PR TITLE
Improved error message when schema agreement fails, as currently it always logs the check took zero milliseconds

### PR DESCRIPTION
**Pull request by maxtomassi**
At the moment, when schema agreement is not reached after the maximum amount of retries, it throws an exception with message:
```
"Failed to reach schema agreement after 0 milliseconds."
```

That's because `count` is used in the error message, but it's value is zero at that point, as we decrement it every time we perform a new retry.

### CODE REVIEW

**Review by dougwettlaufer — APPROVED** [review]

**Comment by dougwettlaufer** [comment]
Hi @maxtomassi looks like the files need reformatted. Can you please run `mvn xml-format:xml-format fmt:format -Pdse`?

**Comment by maxtomassi** [comment]
@dougwettlaufer sorry I missed the formatting check. I've just ran that command and re-pushed. Thanks!

**Review by dimas-b — APPROVED** [review]

**Pull request merged**
