### PR TITLE
Break up searchRows into more reasonable parts

### PR DESCRIPTION
**Pull request by EricBorczuk**
Before this change, searchRows was doing far too much - so I broke it up into 3 reasonable parts.

1) getUnfilteredRows - selects the next page from cassandra
2) getRowsForDocument - selects a page of rows for a particular document
3) getCandidateRows - selects rows for the "candidacy filtering" algorithm we use for evaluating search filters with AND

The common parts of these 3 functions were also refactored (most of them have to do with converting data into C* predicates)

### CODE REVIEW

**Comment by eribeiro** [comment]
Hi @EricBorczuk, I would like to suggest some changes that could be part of this PR.

1) Rename the `addRowsToMap` method to `groupRowsByKey` or `groupByKey`;

2) The following lines in `updateExistenceForMap` can be changed to ``groupByKey(documentChunks, rows)`:

```
    for (int i = 0; i < rows.size(); i++) {
      Row row = rows.get(i);
      String key = row.getString("key");
      List<Row> chunk = documentChunks.getOrDefault(key, new ArrayList<>());
      chunk.add(row);
      documentChunks.put(key, chunk);
    }
```

**Comment by dimas-b** [comment]
I'm actually working on a parallel refactoring under #828 that touches a lot of the code refactored here... it might be worth syncing up on this offline @EricBorczuk :)

**Comment by dimas-b** [comment]
`searchRows` was removed in #937... which should be ready for review/merge soon.

**Comment by EricBorczuk** [comment]
#937 removed searchRows, closing this

**Pull request closed without merging**
