### PR TITLE
Add one Column Resource Unit Tests

### PR DESCRIPTION
**Pull request by FRosner**
This started off as a WIP but I cannot invest more time into additional test cases right now. At least we have the skeleton to easily add more test cases now.

### CODE REVIEW

**Comment by dougwettlaufer** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           

Complexity increasing per file
==============================
- restapi/src/test/java/io/stargate/web/resources/ColumnResourceTest.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/stargate/stargate/pullRequest?prid=6332959&bid=20575262)

**Comment by dougwettlaufer** [comment]
@FRosner can you please sync this up with master to get the latest changes with Google Cloud Build?

**Comment by dougwettlaufer** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           

Complexity increasing per file
==============================
- restapi/src/test/java/io/stargate/web/resources/ColumnResourceTest.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/stargate/stargate/pullRequest?prid=6332959&bid=20575262)

**Comment by dougwettlaufer** [comment]
Build failing on 

```
[INFO] --- fmt-maven-plugin:2.9:check (default) @ restapi ---
[INFO] Processed 58 files (1 non-complying).
[ERROR] Found 1 non-complying files, failing build
[ERROR] To fix formatting errors, run "mvn com.coveo:fmt-maven-plugin:format"
[ERROR] Non complying file: /workspace/restapi/src/test/java/io/stargate/web/resources/ColumnResourceTest.java
```

**Comment by FRosner** [comment]
Yeah no problem it's anyway WIP. However I realized, now that you pointed me to it, that there are tests already inside the `testing` project. Does it even make sense to add the tests here? What's the testing strategy for the project? Should all API tests go to the `testing` module?

**Comment by dougwettlaufer** [comment]
> Does it even make sense to add the tests here? 

Yes, I think it still makes sense to have layered tests. Both integration and unit.

> What's the testing strategy for the project? Should all API tests go to the `testing` module?

Any integration test requiring a live stargate instance should be in the testing module and anything else can live in the corresponding module. @dimas-b do you agree with that?

**Comment by dimas-b** [comment]
> Any integration test requiring a live stargate instance should be in the testing module and anything else can live in the corresponding module. @dimas-b do you agree with that?

+1

Also, I'm in the process of reworking how we deal with Stargate instances in the `testing` module (#254)

**Comment by FRosner** [comment]
I don't want to add more test caes for now as I want to shift focus towards checking out the GraphQL API next. Should I close the PR or update the branch so you can merge the WIP?

**Comment by dougwettlaufer** [comment]
> I don't want to add more test caes for now as I want to shift focus towards checking out the GraphQL API next. Should I close the PR or update the branch and fix the formatting so you can merge the WIP?

We appreciate any new test cases so I'd say get this running and we'll merge it.

**Comment by FRosner** [comment]
I wanted to use the recent Mockito version but it seems there is some conflict with Mockito and PowerMock when it comes to the Dropwizard testing extension.

Then I noticed that we use JUnit 4 in, e.g., the `DocumentResourceV2Test`. Just out of curiosity: Is there a reason to not use JUnit 5? What's the use case of PowerMock here?

**Comment by FRosner** [comment]
I tried to fix it. Also: Could you label with `hacktoberfest-accepted`?

**Comment by dougwettlaufer** [comment]
> I wanted to use the recent Mockito version but it seems there is some conflict with Mockito and PowerMock when it comes to the Dropwizard testing extension.
> 
> Then I noticed that we use JUnit 4 in, e.g., the `DocumentResourceV2Test`. Just out of curiosity: Is there a reason to not use JUnit 5? What's the use case of PowerMock here?

We should be using JUnit 5 everywhere but I believe there was some conflict between it an PowerMock. @EricBorczuk can you remind me why PowerMock is needed?

**Review by dougwettlaufer — APPROVED** [review]

**Pull request merged**
