### PR TITLE
Update `dse-core` dependency from 6.8.21 to 6.8.24

### PR DESCRIPTION
**Pull request by tatu-at-datastax**
**What this PR does**:

Updates `persistence-dse-6.8` to depend on `dse-core` 6.8.24 (from 6.8.21), mostly to update transitive dependencies.

**Which issue(s) this PR fixes**:
No external issue

**Checklist**
- [ ] Changes manually tested
- [ ] Automated Tests added/updated
- [ ] Documentation added/updated
- [ ] CLA Signed: [DataStax CLA](https://cla.datastax.com/)

### CODE REVIEW

**Review by jeffreyscarpenter — APPROVED** [review]
Looks good

**Comment by ivansenic** [comment]
did you also build and push new builder docker image?

**Comment by tatu-at-datastax** [comment]
@ivansenic I don't think so. How is that done? (maybe I missed something from readme of persistence-dse-6.8?)

**Comment by tatu-at-datastax** [comment]
So I did follow version updates but not build... and yes, I think pointing to that would make sense.

**Comment by tatu-at-datastax** [comment]
PR for missing parts: #1906 -- thank you for pointing this out @ivansenic !

**Pull request merged**
