### PR TITLE
Upgrade jetty version because of vulnerability

### PR DESCRIPTION
**Pull request by mpenick**
Resolves: https://github.com/stargate/stargate/security/dependabot/pom.xml/org.eclipse.jetty:jetty-io/open

Dependabot kept upgrading to a major version which breaks our code so I've manually created a PR to resolve the issue.

### CODE REVIEW

**Comment by dimas-b** [comment]
CI has error like this:
```
Step #4 - "cassandra-3.11": INFO  [Exec Stream Pumper] 2021-04-21 14:31:39,957 ProcessRunner.java:78 - stargate12-0> WARN  [dw-264] 2021-04-21 14:31:39,956 HttpChannel.java:677 - /v2/schemas/keyspaces/ks_addRow_1619015498749/tables
Step #4 - "cassandra-3.11": INFO  [Exec Stream Pumper] 2021-04-21 14:31:39,957 ProcessRunner.java:78 - stargate12-0> java.lang.NoSuchMethodError: org.eclipse.jetty.server.Request.setAsyncSupported(ZLjava/lang/String;)V
Step #4 - "cassandra-3.11": INFO  [Exec Stream Pumper] 2021-04-21 14:31:39,957 ProcessRunner.java:78 - stargate12-0> 	at io.dropwizard.jetty.NonblockingServletHolder.handle(NonblockingServletHolder.java:57)
```

**Comment by dougwettlaufer** [comment]
> Do we need to bump DW version too?

Most likely :(

**Comment by mpenick** [comment]
What's DW?

**Comment by dougwettlaufer** [comment]
> What's DW?

Dropwizard

**Comment by mpenick** [comment]
Dropwizard was using an internal API: https://github.com/eclipse/jetty.project/issues/5496

**Review by dimas-b — APPROVED** [review]

**Review by dougwettlaufer — APPROVED** [review]

**Review by ivansenic — COMMENTED** [review]
So after this update the `io.dropwizard.metrics:metrics-core:4.1.19` which is the dependency of the `dropwizard-core` is not in line with the direct dependencies of the metrics which we actually keep in different version. This can even cause trouble, as we overwrite the `metrics-core` version but not the other implicitly pulled by the `dropwizard-core`. 

image

Anyway, @mpenick I'll push the commit that fixes this to this PR, hope that's OK?

**Comment by ivansenic** [comment]
@mpenick @dougwettlaufer @dimas-b I took the liberty to align the `io.dropwizard.metrics` dependencies in the PR and also took out the `metrics-ganglia` dep which is not used at all.. 

Seems I should update the `licenses-report.txt` as well, or? Any idea what's used for that?

**Comment by mpenick** [comment]
> Seems I should update the licenses-report.txt as well, or? Any idea what's used for that?

Looks like a generated file? It hasn't been updated in a bit. Let's do that in another PR.

**Pull request merged**
