### PR TITLE
Get the version of cassandra bundled driver version correct

### PR DESCRIPTION
**Pull request by msmygit**
**What this PR does**: Get the version of cassandra bundled driver version correct

**Which issue(s) this PR fixes**: n/a
Fixes #<issue number>: n/a

**Checklist**
- [ ] Changes manually tested
- [ ] Automated Tests added/updated
- [ ] Documentation added/updated
- [x] CLA Signed: [DataStax CLA](https://cla.datastax.com/)

### CODE REVIEW

**Review by ivansenic — APPROVED** [review]
This looks good now.. What about that test spec in `pom.xml`, we should revert that as well imo

**Comment by msmygit** [comment]
> This looks good now.. What about that test spec in `pom.xml`, we should revert that as well imo

We've discussed and decided to leave the `testing/pom.xml` changes to OSS C* 3.11 system test properties.

**Comment by tatu-at-datastax** [comment]
Ok so this is partial revert of changes done earlier for DSE-6.8.31, right?
I wish I had more strongly asked about version update since I vaguely recalled there being diff versioning scheme for drivers vs Cassandra backend.
Thank you @ivansenic for catching this.

**Pull request merged**
