### PR TITLE
Merge `master` into `v2.0.0`

### PR DESCRIPTION
**Pull request by mpenick**
**What this PR does**:

**Which issue(s) this PR fixes**:
Fixes #<issue number>

**Checklist**
- [x] Changes manually tested
- [ ] Automated Tests added/updated
- [ ] Documentation added/updated
- [ ] CLA Signed: [DataStax CLA](https://cla.datastax.com/)

### CODE REVIEW

**Review by kathirsvn — COMMENTED** [review]
Changes seem fine, straight forward from the master commits, but there are some CI failures.

**Review by ivansenic — CHANGES_REQUESTED** [review]
Hmm seems there is a change here in `test.sh` that looks suspicious:

```
 -./mvnw -B verify --file pom.xml \
 +mvn -B install verify --file pom.xml \
```

And I have no idea how is this hidden in the review here..

**Comment by ivansenic** [comment]
I really tried to understand that change above, the blame points to me as the last person to change that line on the `v2.0.0` branch, but it is an obvious mistake in one of the latest merges, so I am going to fix that.. In addition I'll merge latest versions of both branches..

**Review by ivansenic — APPROVED** [review]
Approving this now :)

**Pull request merged**
