### PR TITLE
upgrade DSE to v6.8.29 in the V2 APIs

### PR DESCRIPTION
**Pull request by versaurabh**
**What this PR does**:
- Upgrades DSE version to 6.8.29

**Checklist**
- [ ] Depends on https://github.com/stargate/stargate/pull/2259 and merge of v1 
- [ ] Changes manually tested
- [x] Automated Tests added/updated
- [ ] Documentation added/updated
- [x] CLA Signed: [DataStax CLA](https://cla.datastax.com/)

### CODE REVIEW

**Comment by ivansenic** [comment]
Hmm dse integrration tests are failing?

**Comment by ivansenic** [comment]
Hmm this does not look good, we are getting the:

```
ava.lang.NoClassDefFoundError: io/netty/handler/codec/compression/Lz4FrameDecoder
INFO  [docker-java-stream-543459670] 2022-11-23 10:09:59,932 null:-1 - [COORDINATOR] STDOUT: 	at org.apache.cassandra.net.async.NettyFactory.createLz4Decoder(NettyFactory.java:340)
```

**Review by ivansenic — CHANGES_REQUESTED** [review]
I am guessing that we need to wait for coordinator to upgrade to `6.8.29` first as well..

**Comment by tatu-at-datastax** [comment]
@versaurabh Usually we do not create separate PRs for `main` and `v1` but rather one PR for `v1` then merge `v1` into `main`. Additional PR is not harmful and may sometimes make sense but is usually not necessary.

**Review by ivansenic — APPROVED** [review]

**Pull request merged**
