### PR TITLE
removing Cassandra 3.11 support

### PR DESCRIPTION
**Pull request by jeffreyscarpenter**
remove support for Cassandra 3.11 persistence as originally proposed in #2242

**Checklist**
- [x] Changes manually tested
- [x] Automated Tests added/updated
- [x] Documentation added/updated
- [x] CLA Signed: [DataStax CLA](https://cla.datastax.com/)

### CODE REVIEW

**Review by tatu-at-datastax — APPROVED** [review]
Yay!

**Comment by tatu-at-datastax** [comment]
One suggestion here, for immediate follow-up: boost version to 2.1.0-SNAPSHOT. This should also allow merging protocolV5 in, to mark "bigger" change.

**Comment by ivansenic** [comment]
Need to remove these there from the needed jobs in order to merge:

```
Integration tests (sgv2-docsapi, cassandra-311) Expected — Waiting for status to be reported
Required
Integration tests (sgv2-graphqlapi, cassandra-311) Expected — Waiting for status to be reported
Required
Integration tests (sgv2-restapi, cassandra-311) Expected — Waiting for status to be reported 
```

**Comment by ivansenic** [comment]
> One suggestion here, for immediate follow-up: boost version to 2.1.0-SNAPSHOT. This should also allow merging protocolV5 in, to mark "bigger" change.

Totally agree, let's change versions to `2.1.0-SNAPSHOT` immediately in this PR.

**Review by ivansenic — APPROVED** [review]
Very good, found only one remaining reference to 3.11:


https://github.com/stargate/stargate/blob/d35109bf1fd9312dfde5312e81963fe3d68d1f49/apis/sgv2-restapi/src/test/java/io/stargate/sgv2/it/RestApiV2QSchemaIndexesIT.java#L221-L224

**Pull request merged**
