### PR TITLE
Merge DSE-6.8.32 changes from v1 to main

### PR DESCRIPTION
**Pull request by tatu-at-datastax**
**What this PR does**:

Merges fix for #2428 into `main` for Stargate V2

**Which issue(s) this PR fixes**:

**Checklist**
- [ ] Changes manually tested
- [ ] Automated Tests added/updated
- [ ] Documentation added/updated
- [x] CLA Signed: [DataStax CLA](https://cla.datastax.com/)

### CODE REVIEW

**Comment by kathirsvn** [comment]
@tatu-at-datastax we have a test failure here.

**Comment by tatu-at-datastax** [comment]
> @tatu-at-datastax we have a test failure here.

Yes, that is that pesky transient failure Ivan was trying to figure out -- cannot reproduce locally, fails frequently once on CI. I'll retry it always seems to disappear on second try for some reason.

**Comment by tatu-at-datastax** [comment]
@kathirsvn Transient failure, ITs passed on retry.

**Review by ivansenic — APPROVED** [review]
This looks good to me..

**Comment by tatu-at-datastax** [comment]
Thanks! merged.

**Pull request merged**
