### PR TITLE
Fix `UnauthorizedException` errors

### PR DESCRIPTION
**Pull request by mpenick**
This unifies `UnauthorizedException` errors into a single type and removes DataStore's version which improves error handling in cqlsh and the drivers. 

This also adds suppressed exceptions to converted exception types where applicable to aid in debugging.

### CODE REVIEW

**Comment by dougwettlaufer** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- persistence-cassandra-4.0/src/main/java/io/stargate/db/cassandra/impl/Conversion.java  1
- persistence-cassandra-3.11/src/main/java/io/stargate/db/cassandra/impl/Conversion.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/stargate/stargate/pullRequest?prid=6301490&bid=20493602)

**Review by dimas-b — DISMISSED** [review]

**Review by dougwettlaufer — DISMISSED** [review]

**Comment by mpenick** [comment]
Oops, I need to fix compile errors.

**Comment by dougwettlaufer** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- persistence-cassandra-3.11/src/main/java/io/stargate/db/cassandra/impl/Conversion.java  1
- persistence-cassandra-4.0/src/main/java/io/stargate/db/cassandra/impl/Conversion.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/stargate/stargate/pullRequest?prid=6301490&bid=20493602)

**Review by dimas-b — APPROVED** [review]

**Comment by dougwettlaufer** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- persistence-cassandra-3.11/src/main/java/io/stargate/db/cassandra/impl/Conversion.java  1
- persistence-cassandra-4.0/src/main/java/io/stargate/db/cassandra/impl/Conversion.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/stargate/stargate/pullRequest?prid=6301490&bid=20493602)

**Pull request merged**
